// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArPP5b5DuhpzvrWQOZZOHxV1oENXHF-Lg',
    appId: '1:820692517762:web:faa4ac83a8eca5fbf7859b',
    messagingSenderId: '820692517762',
    projectId: 'moviemate-df547',
    authDomain: 'moviemate-df547.firebaseapp.com',
    storageBucket: 'moviemate-df547.appspot.com',
    measurementId: 'G-JV9BWDQ8EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRoqX_EQAnTJDmCakkNEfoTYLhz5_iB0',
    appId: '1:820692517762:android:e2e8168eb3c13b89f7859b',
    messagingSenderId: '820692517762',
    projectId: 'moviemate-df547',
    storageBucket: 'moviemate-df547.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjClk_DH9UnMLtC8aV-l7bOZbysn-54yg',
    appId: '1:820692517762:ios:5065e41d255b922ff7859b',
    messagingSenderId: '820692517762',
    projectId: 'moviemate-df547',
    storageBucket: 'moviemate-df547.appspot.com',
    iosBundleId: 'com.moviemate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjClk_DH9UnMLtC8aV-l7bOZbysn-54yg',
    appId: '1:820692517762:ios:5065e41d255b922ff7859b',
    messagingSenderId: '820692517762',
    projectId: 'moviemate-df547',
    storageBucket: 'moviemate-df547.appspot.com',
    iosBundleId: 'com.moviemate.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArPP5b5DuhpzvrWQOZZOHxV1oENXHF-Lg',
    appId: '1:820692517762:web:d6ffe0d35a879314f7859b',
    messagingSenderId: '820692517762',
    projectId: 'moviemate-df547',
    authDomain: 'moviemate-df547.firebaseapp.com',
    storageBucket: 'moviemate-df547.appspot.com',
    measurementId: 'G-J656Y2MR5V',
  );
}
